AWSTemplateFormatVersion: 2010-09-09
Description: Template for creating API Gateway configuration

Parameters:

  HostedZoneName:
    Type: String
    Description: The Domain name of the API
    Default: polimetla.de # Do not include a trailing period here

  CertificateId:
    Type: String
    Description: The ID of the SSL Certificate
    Default: bc5d0691-d3b6-4796-9c24-afa6724d3bd3 # Same for all environments. *.DomainName

  UsagePlanName:
    Type: String
    Description: Name of the Usage Plan
    Default: DevUsagePlan
    AllowedValues: [ DevUsagePlan, UATUsagePlan, ProdUsagePlan ]
    
  Environment:
    Type: String
    Description: The environment for the deployment
    Default: dev
    AllowedValues: [ dev, uat, prod ]

  QuotaLimit:
    Type: Number
    Description: The requests Quota Limit
    Default: 1000
  
  QuotaPeriod:
    Type: String
    Description: The Quota Period type (e.g. DAY,WEEK,MONTH)
    Default: MONTH
    
  ThrottleBurstLimit:
    Type: Number
    Description: The requests Burst Limit
    Default: 200
  
  ThrottleRateLimit:
    Type: Number
    Description: The requests per second Rate Limit
    Default: 100

Resources:

  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties: 
      Quota:
        Limit: !Ref QuotaLimit
        Period: !Ref QuotaPeriod
      Throttle:
        BurstLimit: !Ref ThrottleBurstLimit
        RateLimit: !Ref ThrottleRateLimit    
      UsagePlanName: !Ref UsagePlanName
    
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: api-key
      Enabled: true

  ApiKeyAssociation: # Associates a API key with a usage plan
    Type: AWS::ApiGateway::UsagePlanKey
    Properties: 
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiUsagePlan

  ApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties: 
      DomainName: !Sub api-${Environment}.${HostedZoneName}
      EndpointConfiguration:
        Types:
          - REGIONAL
      SecurityPolicy: TLS_1_2   
      RegionalCertificateArn: !Sub arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/${CertificateId}

  ApiRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub ${HostedZoneName}. # Trailing period is necessary
      Name: !Ref ApiDomainName
      ResourceRecords:
        - !GetAtt ApiDomainName.RegionalDomainName
      TTL: 60
      Type: CNAME

Outputs:
  DomainName:
    Description: The Domain name
    Value: !Ref ApiDomainName
    Export:
      Name: ApiGateway-DomainName